// Generated for: netutils 1.0.0.0
// Generated by: Microsoft.JavaScript.NodeApi.Generator 0.4.0.0
/* eslint-disable */


declare module 'node-api-dotnet' {

	export function getAPIVersion(apiPath: string): number;

	export function getGameVersion(apiPath: string): string;

	export function tryFindGamePath(): string | undefined;
}
