
name: Build Electron App

on:
  push

jobs:

  release:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: HKMM-UI/package-lock.json
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Build NetUtils
        run: |
          dotnet build
      - name: Build Game Inject
        run: |
          cd gameinject
          npm install
          npm run build
      - name: npm install
        run: |
          cd HKMM-UI
          npm ci
      - name: Build
        run: |
          cd HKMM-UI
          npm run electron:build
          npm run build:update
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            HKMM-UI/dist_electron/*.exe
            HKMM-UI/dist_electron/update.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: setup
          path: "HKMM-UI/dist_electron/*.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: update
          path: "HKMM-UI/dist_electron/update.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      