// Generated for: core 1.0.0.0
// Generated by: Microsoft.JavaScript.NodeApi.Generator 0.31.0.0
/* eslint-disable */


declare module "core" {

	export function registerLogHandler(
		level: string,
		handler: (arg1: string) => void,
	): void;

	export function getAPIVersion(apiPath: string): number;

	export function getGameVersion(apiPath: string): string;

	export function tryFindGamePath(): string | undefined;

	export function test(pack: ResourcePackage): void;

	export interface TaskPropertyChanged { (
		task: TaskItem,
		propertyName: string | undefined,
	): void; }

	export class TaskLogInfo {
		message: string;

		color?: string;
	}

	export class TaskItem {
		constructor();

		name: string;

		guid: string;

		progress: number;

		readonly startTime: Date;

		endTime: Date;

		onChanged?: TaskPropertyChanged;

		status: TaskItemStatus;

		readonly isSuccess: boolean;

		readonly isFailed: boolean;

		readonly isRunning: boolean;

		isHidden: boolean;

		readonly logCount: number;

		getLogAt(id: number): TaskLogInfo;

		log(msg: string): void;

		logError(msg: string): void;

		logWarn(msg: string): void;

		print(
			msg: string,
			level: unknown,
		): void;

		getRunningTime(): number;
	}

	export enum TaskItemStatus {
		Idle = 0,

		Running = 1,

		Success = 2,

		Fail = 3,
	}

	export namespace TaskManager {
		export const taskCount: number;

		export function getTaskAt(id: number): TaskItem;

		export function startTask(task: TaskItem): void;

		export function getTask(guid: string): TaskItem | undefined;

		export function getTasksProgress(): number;
	}

	export class ResourcePackage {
		name: string;

		guid: string;

		type: ResourceResovleType;

		displayName?: string;

		description?: string;

		version: string;

		authors: string[];

		resources: ResourceResovle[];
	}

	export enum ResourcePackageType {
		None = 0,

		Mod = 1,

		Modpack = 2,
	}

	export class ResourceResovle {
		type: ResourceResovleType;

		data: string;
	}

	export enum ResourceResovleType {
		None = 0,

		WebFile = 1,
	}
}
